// brain-3d.jsx
// A volumetric 3D particle-cloud brain - fully procedural, NOT a 2D
// silhouette extruded into depth. The shape is generated by a parametric
// brain function: an anatomically-proportioned ellipsoid with a
// longitudinal fissure down the middle, a cerebellum bulge at the back,
// and noise-based sulci on the surface. Particles fill the volume so the
// cloud has real shape from every angle.
//
// Drag to rotate. 5 hub neurons sit on the surface and are projected to
// HTML labels each frame.

// Information clusters - concentrations of "memories" / "thoughts".
const N_CORTEX_CLUSTERS = 180; // discrete neighborhoods
const N_CEREB_CLUSTERS = 28;
const PARTICLES_PER_CLUSTER_AVG = 95; // particles tightly grouped per cluster
const N_CORTEX_FOG = 1800; // a wisp of looser background points
const POINT_SIZE = 0.02;
const BRAIN_SCALE = 1.55; // overall scale-up to fill the frame
const ROTATE_SENSITIVITY = 0.005;

// Axis convention:
//   x: lateral (left -, right +)
//   y: anterior-posterior (front +, back -)   ← top of screen = front of head when viewed top-down
//   z: inferior-superior (top +, bottom -)
// Camera starts on +z looking down at the brain (top-down view), matching the 2D version.

// ── Procedural brain shape ─────────────────────────────────────────────
// Returns the surface radius of the cortex in the direction (dx,dy,dz).
// (dx,dy,dz) must be a unit vector.
function cortexRadius(dx, dy, dz) {
  // Anatomical-ish ellipsoid: longest front-back (y), narrower top-bottom (z).
  const a = 1.0,
    b = 1.22,
    c = 0.88;
  let r =
    1 /
    Math.sqrt((dx * dx) / (a * a) + (dy * dy) / (b * b) + (dz * dz) / (c * c));

  // Frontal lobe is slightly fuller; occipital tapers.
  if (dy > 0) r *= 1.0 + 0.04 * dy;
  else r *= 1.0 + 0.05 * dy; // dy<0 → shrink

  // Bottom of brain flattens (where it meets brainstem).
  if (dz < -0.45) r *= 1.0 - 0.18 * (-dz - 0.45);

  // Temporal lobe bulges on the lower lateral sides.
  const lateralLow = Math.max(0, Math.abs(dx) - 0.45) * Math.max(0, -dz - 0.05);
  r += 0.12 * lateralLow;

  // Sulci/gyri: deeper, more pronounced 3D wavy perturbation. Sum of
  // sines = cheap pseudo-noise; we crank amplitude so the brain reads as
  // bumpy/folded from any angle rather than smooth ellipsoidal.
  const sulci =
    0.075 * Math.sin(dx * 6.8 + dy * 5.1) * Math.cos(dz * 6.5) +
    0.06 * Math.cos(dy * 8.2 + dz * 4.3) * Math.sin(dx * 5.7) +
    0.05 * Math.sin(dx * 6.5 + dy * 7.9 + dz * 5.3) +
    0.04 * Math.cos(dx * 10.5) * Math.sin(dy * 8.7) +
    0.03 * Math.sin(dz * 11.3 + dx * 4.9);
  r += sulci;

  return r;
}

// Cerebellum: a smaller, denser blob attached at the back-bottom.
const CEREB_CENTER = [0, -0.78, -0.42];
const CEREB_RADIUS = 0.42;

function cerebellumRadius(dx, dy, dz) {
  const a = 1.0,
    b = 0.85,
    c = 0.75;
  let r =
    1 /
    Math.sqrt((dx * dx) / (a * a) + (dy * dy) / (b * b) + (dz * dz) / (c * c));
  // Tight folia ridges (cerebellum has very fine folds in real life).
  r += 0.04 * Math.sin(dy * 18 + dx * 4) + 0.03 * Math.sin(dz * 14);
  return r * CEREB_RADIUS;
}

// Probability that a particle survives the longitudinal fissure (the deep
// groove between hemispheres along the y-axis at x≈0). Returns 0..1.
function fissureKeep(x, y, z) {
  // Fissure runs along y, from front to mid-back, only on the dorsal half.
  // Don't carve the fissure into the underside.
  if (z < -0.1) return 1;
  // Don't carve at the very front tip (frontal pole curves around).
  const ySoftStart = Math.max(0, 1 - Math.abs(y - 0.0) / 1.1);
  const fissureWidth = 0.05 * ySoftStart;
  const dx = Math.abs(x);
  if (dx > fissureWidth + 0.04) return 1;
  // Falloff
  const t = Math.max(0, (dx - 0) / (fissureWidth + 0.04));
  return Math.max(0.05, t);
}

// Hub positions in the SAME anatomical coords. We'll snap each onto the
// cortex surface so they sit on the cloud regardless of shape tweaks.
const HUBS_3D = [
  {
    id: "ideas",
    label: "Ideas & projects",
    stat: "34 active",
    recent: "2 days ago",
    region: "Frontal",
    dir: [-0.45, 0.8, 0.4],
  },
  {
    id: "journal",
    label: "Daily journal",
    stat: "127 entries",
    recent: "this morning",
    region: "Prefrontal",
    dir: [-0.75, 0.55, 0.35],
  },
  {
    id: "health",
    label: "Health metrics",
    stat: "6 streams",
    recent: "syncing now",
    region: "Cerebellum",
    dir: [0.3, -0.85, -0.3],
    cerebellum: true,
  },
  {
    id: "people",
    label: "People",
    stat: "218 nodes",
    recent: "yesterday",
    region: "Temporal",
    dir: [-0.55, -0.3, -0.55],
  },
  {
    id: "travel",
    label: "Travel",
    stat: "14 places",
    recent: "last month",
    region: "Parietal",
    dir: [0.55, 0.2, 0.75],
  },
];

// Snap each hub direction to the actual surface of the chosen region.
function computeHubPositions() {
  return HUBS_3D.map((h) => {
    const len = Math.hypot(h.dir[0], h.dir[1], h.dir[2]);
    const ux = h.dir[0] / len,
      uy = h.dir[1] / len,
      uz = h.dir[2] / len;
    let pos;
    if (h.cerebellum) {
      const r = cerebellumRadius(ux, uy, uz);
      pos = [
        CEREB_CENTER[0] + ux * r * 1.05,
        CEREB_CENTER[1] + uy * r * 1.05,
        CEREB_CENTER[2] + uz * r * 1.05,
      ];
    } else {
      const r = cortexRadius(ux, uy, uz) * 1.06; // sit just outside surface
      pos = [ux * r, uy * r, uz * r];
    }
    return { ...h, pos };
  });
}

function Brain3D({ onHubHover, onHubClick, activeHub, expandedHub }) {
  const mountRef = React.useRef(null);
  const stateRef = React.useRef({});
  const [ready, setReady] = React.useState(false);
  const [hubScreen, setHubScreen] = React.useState([]);

  React.useEffect(() => {
    if (!window.THREE) {
      console.error("THREE not loaded");
      return;
    }
    const THREE = window.THREE;
    const mount = mountRef.current;
    const r = mount.getBoundingClientRect();

    // ── Scene setup ───────────────────────────────────────────────────
    const scene = new THREE.Scene();
    // Tighter FOV + closer camera = brain fills more of the frame.
    const camera = new THREE.PerspectiveCamera(
      32,
      r.width / r.height,
      0.1,
      1000,
    );
    camera.position.set(0, 0, 4.6);

    const renderer = new THREE.WebGLRenderer({ antialias: true, alpha: true });
    renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));
    renderer.setSize(r.width, r.height);
    renderer.setClearColor(0x000000, 0);
    mount.appendChild(renderer.domElement);

    // Group rotated by drag, then a child group rotated to make initial
    // view top-down (looking down +z onto the brain).
    const root = new THREE.Group();
    const tilt = new THREE.Group();
    // Rotate -90° around X so +z (top of head) points toward camera, +y
    // (front of head) points up on screen.
    tilt.rotation.x = -Math.PI / 2;
    root.add(tilt);
    scene.add(root);

    // ── Soft round point sprite ────────────────────────────────────────
    const makeSprite = () => {
      const c = document.createElement("canvas");
      c.width = c.height = 64;
      const ctx = c.getContext("2d");
      const g = ctx.createRadialGradient(32, 32, 0, 32, 32, 32);
      g.addColorStop(0, "rgba(255,255,255,1)");
      g.addColorStop(0.25, "rgba(220,238,255,0.85)");
      g.addColorStop(0.55, "rgba(156,213,255,0.30)");
      g.addColorStop(1, "rgba(156,213,255,0)");
      ctx.fillStyle = g;
      ctx.fillRect(0, 0, 64, 64);
      const t = new THREE.CanvasTexture(c);
      t.minFilter = THREE.LinearFilter;
      return t;
    };
    const sprite = makeSprite();

    // ── Sample volumetric particles ────────────────────────────────────
    // Seeded RNG for stable particle layout across reloads.
    const rng = (() => {
      let s = 17;
      return () => {
        s = (s * 9301 + 49297) % 233280;
        return s / 233280;
      };
    })();

    // Gaussian sample (Box–Muller) for cluster-local jitter.
    const gauss = () => {
      const u1 = Math.max(1e-6, rng()),
        u2 = rng();
      return Math.sqrt(-2 * Math.log(u1)) * Math.cos(2 * Math.PI * u2);
    };

    // Pick a uniform direction on the unit sphere.
    const randDir = () => {
      let dx, dy, dz, len2;
      do {
        dx = rng() * 2 - 1;
        dy = rng() * 2 - 1;
        dz = rng() * 2 - 1;
        len2 = dx * dx + dy * dy + dz * dz;
      } while (len2 > 1 || len2 < 0.0001);
      const len = Math.sqrt(len2);
      return [dx / len, dy / len, dz / len];
    };

    // Build cortex CLUSTER CENTERS - each becomes a tight knot of particles
    // (a "concentration of information"). Centers sit between mid-depth and
    // the surface so clusters live in the cortical shell.
    const cortexClusters = [];
    while (cortexClusters.length < N_CORTEX_CLUSTERS) {
      const [dx, dy, dz] = randDir();
      const R = cortexRadius(dx, dy, dz);
      // Place center in outer ~55% of the cortex - concentrations live near surface.
      const u = 0.55 + rng() * 0.42;
      const cx = dx * R * u,
        cy = dy * R * u,
        cz = dz * R * u;
      // Skip clusters that would land inside the longitudinal fissure.
      if (rng() > fissureKeep(cx, cy, cz)) continue;
      // Vary cluster size: most are small/tight, a few larger.
      const sizeRoll = rng();
      const sigma =
        sizeRoll < 0.7
          ? 0.045 + rng() * 0.025
          : sizeRoll < 0.93
            ? 0.075 + rng() * 0.03
            : 0.105 + rng() * 0.03;
      const count = Math.round(
        PARTICLES_PER_CLUSTER_AVG *
          (0.55 + rng() * 0.9) *
          (sigma > 0.085 ? 1.5 : 1),
      );
      cortexClusters.push({ cx, cy, cz, sigma, count, kind: "cortex" });
    }

    const cerebClusters = [];
    while (cerebClusters.length < N_CEREB_CLUSTERS) {
      const [dx, dy, dz] = randDir();
      const R = cerebellumRadius(dx, dy, dz);
      const u = 0.55 + rng() * 0.4;
      cerebClusters.push({
        cx: CEREB_CENTER[0] + dx * R * u,
        cy: CEREB_CENTER[1] + dy * R * u,
        cz: CEREB_CENTER[2] + dz * R * u,
        sigma: 0.03 + rng() * 0.025,
        count: Math.round(
          PARTICLES_PER_CLUSTER_AVG * 0.6 * (0.6 + rng() * 0.7),
        ),
        kind: "cereb",
      });
    }

    // Estimate total particle count to size the buffer.
    const totalEst =
      cortexClusters.reduce((a, c) => a + c.count, 0) +
      cerebClusters.reduce((a, c) => a + c.count, 0) +
      N_CORTEX_FOG +
      200;
    const positions = new Float32Array(3 * totalEst);
    const colors = new Float32Array(3 * totalEst);
    let ptr = 0;

    const writePoint = (x, y, z, kind) => {
      if (ptr * 3 + 2 >= positions.length) return;
      positions[ptr * 3] = x;
      positions[ptr * 3 + 1] = y;
      positions[ptr * 3 + 2] = z;
      // Subtle vertical gradient: brighter up top, slightly dim underneath.
      const top = (z + 0.9) / 1.8;
      const front = (y + 1.2) / 2.4;
      let rC, gC, bC;
      if (kind === "cereb") {
        rC = 0.55 + 0.1 * top;
        gC = 0.78 + 0.1 * top;
        bC = 0.96;
      } else {
        rC = 0.5 + 0.3 * top + 0.05 * front;
        gC = 0.74 + 0.2 * top + 0.04 * front;
        bC = 0.92 + 0.08 * top;
      }
      colors[ptr * 3] = rC;
      colors[ptr * 3 + 1] = gC;
      colors[ptr * 3 + 2] = bC;
      ptr++;
    };

    // Render each cluster: particles are tightly grouped around the center.
    const renderCluster = (cl) => {
      const cR = cortexRadius; // for clamping cortex points to surface
      for (let i = 0; i < cl.count; i++) {
        // Anisotropic Gaussian - stretch slightly tangent to surface so
        // clusters look like tiny ridges, not perfect balls.
        const jx = gauss() * cl.sigma;
        const jy = gauss() * cl.sigma;
        const jz = gauss() * cl.sigma * 0.7;
        let x = cl.cx + jx;
        let y = cl.cy + jy;
        let z = cl.cz + jz;
        if (cl.kind === "cortex") {
          // Clamp to inside the cortex shape so clusters don't leak outside.
          const len = Math.hypot(x, y, z);
          if (len > 0.0001) {
            const ux = x / len,
              uy = y / len,
              uz = z / len;
            const Rmax = cR(ux, uy, uz) * 1.02;
            if (len > Rmax) {
              x = ux * Rmax;
              y = uy * Rmax;
              z = uz * Rmax;
            }
          }
          if (rng() > fissureKeep(x, y, z)) continue;
        }
        writePoint(x, y, z, cl.kind);
      }
    };
    cortexClusters.forEach(renderCluster);
    cerebClusters.forEach(renderCluster);

    // Sparse background "fog" - a faint scatter that fills the volume so
    // the brain shape is still readable between clusters.
    let fogMade = 0;
    while (fogMade < N_CORTEX_FOG) {
      const [dx, dy, dz] = randDir();
      const R = cortexRadius(dx, dy, dz);
      const u = Math.pow(rng(), 0.6);
      const r = R * u * 0.96;
      const x = dx * r,
        y = dy * r,
        z = dz * r;
      if (rng() > fissureKeep(x, y, z)) continue;
      writePoint(x, y, z, "cortex");
      fogMade++;
    }

    // Apply overall scale so the brain takes up more of the frame.
    for (let i = 0; i < ptr * 3; i++) positions[i] *= BRAIN_SCALE;

    const geom = new THREE.BufferGeometry();
    geom.setAttribute(
      "position",
      new THREE.BufferAttribute(positions.slice(0, ptr * 3), 3),
    );
    geom.setAttribute(
      "color",
      new THREE.BufferAttribute(colors.slice(0, ptr * 3), 3),
    );
    const mat = new THREE.PointsMaterial({
      size: POINT_SIZE,
      map: sprite,
      transparent: true,
      depthWrite: false,
      blending: THREE.AdditiveBlending,
      vertexColors: true,
    });
    const cloud = new THREE.Points(geom, mat);
    tilt.add(cloud);

    // ── Hub markers (sprites) ─────────────────────────────────────────
    const hubsResolved = computeHubPositions();
    const hubGroup = new THREE.Group();
    const hubMeshes = [];
    const hubSpriteTex = (() => {
      const c = document.createElement("canvas");
      c.width = c.height = 128;
      const ctx = c.getContext("2d");
      const g = ctx.createRadialGradient(64, 64, 0, 64, 64, 64);
      g.addColorStop(0, "rgba(255,255,255,1)");
      g.addColorStop(0.18, "rgba(220,238,255,1)");
      g.addColorStop(0.4, "rgba(156,213,255,0.7)");
      g.addColorStop(1, "rgba(156,213,255,0)");
      ctx.fillStyle = g;
      ctx.fillRect(0, 0, 128, 128);
      return new THREE.CanvasTexture(c);
    })();

    hubsResolved.forEach((h, i) => {
      const sm = new THREE.SpriteMaterial({
        map: hubSpriteTex,
        color: 0xffffff,
        transparent: true,
        blending: THREE.AdditiveBlending,
        depthWrite: false,
      });
      const s = new THREE.Sprite(sm);
      s.scale.set(0.32, 0.32, 1);
      s.position.set(
        h.pos[0] * BRAIN_SCALE,
        h.pos[1] * BRAIN_SCALE,
        h.pos[2] * BRAIN_SCALE,
      );
      s.userData.idx = i;
      hubGroup.add(s);
      hubMeshes.push(s);
    });
    tilt.add(hubGroup);
    stateRef.current.hubMeshes = hubMeshes;
    stateRef.current.hubsResolved = hubsResolved;
    stateRef.current.cloud = cloud;

    setReady(true);

    // ── Drag to rotate ────────────────────────────────────────────────
    // Initial tilt: a small lean so we can see it's volumetric immediately.
    let rotY = 0.0,
      rotX = 0.25;
    let dragging = false;
    let lastX = 0,
      lastY = 0;
    let autoRot = true;

    const onDown = (e) => {
      dragging = true;
      autoRot = false;
      const p = e.touches ? e.touches[0] : e;
      lastX = p.clientX;
      lastY = p.clientY;
    };
    const onMove = (e) => {
      if (!dragging) return;
      const p = e.touches ? e.touches[0] : e;
      const dx = p.clientX - lastX,
        dy = p.clientY - lastY;
      lastX = p.clientX;
      lastY = p.clientY;
      rotY += dx * ROTATE_SENSITIVITY;
      rotX += dy * ROTATE_SENSITIVITY;
      rotX = Math.max(-1.3, Math.min(1.3, rotX));
    };
    const onUp = () => {
      dragging = false;
    };

    renderer.domElement.style.touchAction = "none";
    renderer.domElement.addEventListener("pointerdown", onDown);
    window.addEventListener("pointermove", onMove);
    window.addEventListener("pointerup", onUp);

    // ── Resize ────────────────────────────────────────────────────────
    const onResize = () => {
      const r = mount.getBoundingClientRect();
      camera.aspect = r.width / r.height;
      camera.updateProjectionMatrix();
      renderer.setSize(r.width, r.height);
    };
    const ro = new ResizeObserver(onResize);
    ro.observe(mount);

    // ── Hub picking ───────────────────────────────────────────────────
    const raycaster = new THREE.Raycaster();
    const mouse = new THREE.Vector2();
    const onHover = (e) => {
      const rect = renderer.domElement.getBoundingClientRect();
      mouse.x = ((e.clientX - rect.left) / rect.width) * 2 - 1;
      mouse.y = -((e.clientY - rect.top) / rect.height) * 2 + 1;
      raycaster.setFromCamera(mouse, camera);
      const hits = raycaster.intersectObjects(hubMeshes, false);
      if (hits.length) {
        if (onHubHover) onHubHover(hits[0].object.userData.idx);
        renderer.domElement.style.cursor = "pointer";
      } else {
        if (onHubHover) onHubHover(null);
        renderer.domElement.style.cursor = dragging ? "grabbing" : "grab";
      }
    };
    const onCanvasClick = (e) => {
      const rect = renderer.domElement.getBoundingClientRect();
      mouse.x = ((e.clientX - rect.left) / rect.width) * 2 - 1;
      mouse.y = -((e.clientY - rect.top) / rect.height) * 2 + 1;
      raycaster.setFromCamera(mouse, camera);
      const hits = raycaster.intersectObjects(hubMeshes, false);
      if (hits.length && onHubClick) onHubClick(hits[0].object.userData.idx);
    };
    renderer.domElement.addEventListener("pointermove", onHover);
    renderer.domElement.addEventListener("click", onCanvasClick);
    renderer.domElement.style.cursor = "grab";

    // ── Animate ───────────────────────────────────────────────────────
    let raf;
    const t0 = performance.now();
    const tick = () => {
      const now = performance.now();
      const t = (now - t0) / 1000;
      if (autoRot) rotY += 0.0018;
      root.rotation.y += (rotY - root.rotation.y) * 0.12;
      root.rotation.x += (rotX - root.rotation.x) * 0.12;

      // Hub pulse + selection scaling
      const cur = stateRef.current.activeHub;
      hubMeshes.forEach((m, i) => {
        const base = 0.3 + Math.sin(t * 1.4 + i) * 0.025;
        const big = i === cur ? 1.55 : 1.0;
        m.scale.set(base * big, base * big, 1);
      });

      // Project hub world positions to screen for HTML overlays
      const out = [];
      const v = new THREE.Vector3();
      const screenRect = renderer.domElement.getBoundingClientRect();
      hubMeshes.forEach((m, i) => {
        m.getWorldPosition(v);
        v.project(camera);
        out.push({
          x: (v.x * 0.5 + 0.5) * screenRect.width,
          y: (-v.y * 0.5 + 0.5) * screenRect.height,
          z: v.z,
          idx: i,
        });
      });
      // Throttle setState to every other frame.
      if (((now / 16) | 0) % 2 === 0) setHubScreen(out);

      renderer.render(scene, camera);
      raf = requestAnimationFrame(tick);
    };
    raf = requestAnimationFrame(tick);

    return () => {
      cancelAnimationFrame(raf);
      ro.disconnect();
      renderer.domElement.removeEventListener("pointerdown", onDown);
      renderer.domElement.removeEventListener("pointermove", onHover);
      renderer.domElement.removeEventListener("click", onCanvasClick);
      window.removeEventListener("pointermove", onMove);
      window.removeEventListener("pointerup", onUp);
      mount.removeChild(renderer.domElement);
      renderer.dispose();
    };
  }, []);

  React.useEffect(() => {
    stateRef.current.activeHub = activeHub;
  }, [activeHub]);

  const ICE = window.ICE_PALETTE || {
    hi: "#e6f4ff",
    accent: "#9cd5ff",
    low: "rgba(190,220,255,0.45)",
  };

  return (
    <div
      ref={mountRef}
      style={{ position: "absolute", inset: 0, zIndex: 1, overflow: "hidden" }}
    >
      {ready &&
        hubScreen.map((h) => {
          const cat = HUBS_3D[h.idx];
          const isActive = h.idx === activeHub || h.idx === expandedHub;
          // Fade labels when they're on the back side of the cloud.
          const opacity = h.z < 0.55 ? 1 : Math.max(0, 1 - (h.z - 0.55) * 4);
          return (
            <div
              key={cat.id}
              data-hub-idx={h.idx}
              style={{
                position: "absolute",
                left: h.x,
                top: h.y,
                transform: "translate(-50%, -50%)",
                pointerEvents: "none",
                opacity,
                transition: "opacity 0.3s ease",
                fontFamily: "Inter, system-ui, sans-serif",
                zIndex: 4,
              }}
            >
              <div
                style={{
                  transform: `translate(0, ${22 + (isActive ? 4 : 0)}px)`,
                  textAlign: "center",
                  minWidth: 110,
                  userSelect: "none",
                }}
              >
                <div
                  style={{
                    fontSize: 9,
                    letterSpacing: 1.8,
                    textTransform: "uppercase",
                    color: ICE.accent,
                    opacity: 0.7,
                    fontFamily: "ui-monospace, monospace",
                    marginBottom: 3,
                  }}
                >
                  {cat.region}
                </div>
                <div
                  style={{
                    fontFamily: '"Cormorant Garamond", serif',
                    fontSize: 16,
                    lineHeight: 1.15,
                    color: ICE.hi,
                    letterSpacing: 0.2,
                    fontStyle: "italic",
                    whiteSpace: "nowrap",
                  }}
                >
                  {cat.label}
                </div>
                <div
                  style={{
                    fontSize: 10,
                    color: ICE.low,
                    marginTop: 3,
                    letterSpacing: 0.4,
                    whiteSpace: "nowrap",
                  }}
                >
                  {cat.stat}
                </div>
              </div>
            </div>
          );
        })}
      {!ready && (
        <div
          style={{
            position: "absolute",
            left: "50%",
            top: "50%",
            transform: "translate(-50%,-50%)",
            fontSize: 11,
            letterSpacing: 2,
            color: "rgba(190,220,255,0.45)",
            textTransform: "uppercase",
          }}
        >
          composing neurons…
        </div>
      )}
    </div>
  );
}

Object.assign(window, { Brain3D, BRAIN_HUBS_3D: HUBS_3D });
